FROM alpine:latest
RUN apk update && apk upgrade && apk --no-cache add \
    bash \
    curl \
    git \
    unzip \
    apache2 \
    apache2-utils \
    icu-dev \
    libzip-dev \
    oniguruma-dev \
    build-base \
    php82 \
    php82-cli \
    php82-common \
    php82-ctype \
    php82-curl \
    php82-dom \
    php82-gd \
    php82-iconv \
    php82-intl \
    php82-json \
    php82-mbstring \
    php82-openssl \
    php82-pdo \
    php82-pdo_mysql \
    php82-simplexml \
    php82-xml \
    php82-xmlreader \
    php82-xmlwriter \
    php82-tokenizer \
    php82-zip \
    php82-session \
    php82-phar \
    php82-fileinfo \
    php82-opcache \
    php82-sodium \
    php82-bcmath \
    php82-exif \
    php82-ftp \
    php82-posix \
    php82-sockets